### ISSUE TITLE
Does not work with PowerDNS 3.4.1 and NodeJS 0.10.40

### ISSUE THREAD

**Issue by vladsol** [xbgmsharp/yapdnsui#4]
Hello.

Installed, as described in https://github.com/xbgmsharp/yapdnsui
I can (and added) server to UI, But, when i trying to select server, i got an error in console:

SyntaxError: Unexpected token U
    at Object.parse (native)
    at /home/vlad/yapdnsui/routes/pdns.js:66:57
    at Request._callback (/home/vlad/yapdnsui/libs/pdnsapi.js:15:25)
    at Request.self.callback (/home/vlad/yapdnsui/node_modules/request/request.js:121:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/vlad/yapdnsui/node_modules/request/request.js:985:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/vlad/yapdnsui/node_modules/request/request.js:936:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16

npm ERR! yapdnsui@0.0.4-9ca2a02 start: `DEBUG=yapdnsui node ./bin/www`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the yapdnsui@0.0.4-9ca2a02 start script.
npm ERR! This is most likely a problem with the yapdnsui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     DEBUG=yapdnsui node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls yapdnsui
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.32-358.23.2.el6.i686
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /home/vlad/yapdnsui
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/vlad/yapdnsui/npm-debug.log
npm ERR! not ok code 0

**Comment by vladsol** [comment]
My diff: http://pastebin.com/0jkQPyJe
Here i changed basic auth to the api key auth.

**Comment by xbgmsharp** [comment]
Fix via commit ﻿﻿https://github.com/xbgmsharp/yapdnsui/commit/6f1c19f54dd78cbf2310fb1c04cd4e890dd226c5

**Comment by xbgmsharp** [comment]
New release!
https://github.com/xbgmsharp/yapdnsui/releases/tag/v0.0.5-c4bc57c
